version: '3.8'

services:
  ftp-server:
    build: ../build
    container_name: ftp-anonymous-vuln-lab
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - PASV_ADDRESS=${PASV_ADDRESS:-127.0.0.1}
    volumes:
      - ftp_logs:/var/log
    restart: unless-stopped
    networks:
      - ftp-network
    labels:
      - "vulnerability.ftp.anonymous=true"
      - "educational.purpose=true"

networks:
  ftp-network:
    driver: bridge

volumes:
  ftp_logs:
    driver: local 